# Generated by Django 2.2.10 on 2021-12-02 09:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='participant',
        ),
        migrations.AddField(
            model_name='survey',
            name='participants',
            field=models.ManyToManyField(related_name='surveys', to=settings.AUTH_USER_MODEL, verbose_name='Участник'),
        ),
    ]
